dispatcher/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.BBLoginView.as_view(), name='login'),
    path('accounts/login/', views.BBLogoutView.as_view(), name='logout'),
    path('profile/',views.profile,name='profile'),
    path('logout/', views.BBLogoutView.as_view(), name='logout'),
    path('', views.home, name='create'),
    # path('register/', views.register, name='create'),
    path('act/',views.act_page_create, name='act'),
    path('list/',views.act_list, name='act_list'),
    path('act/<int:pk>/edit/',views.act_edit_form, name='act-edit-form'),
    re_path(r'^act/(?P<actid>\d+)/$',views.act_page, name='act_page'),
    path('dispatcher/list',views.dispatcher_act_list,name='dispatcher-act-list'),
    re_path(r'^act/(?P<actid>\d+)/return/$', views.return_act, name='return-act'),
    re_path(r'^act/(?P<actid>\d+)/accept/$', views.accept_act, name='return-act'),
    re_path(r'^act/(?P<actid>\d+)/date/$', views.set_date, name='set-date'),
    path('employees/', views.employees_list, name='employees_list'),
    path('dispatcher/status/',views.act_status, name='act-status'),
    path('dispatcher/search',views.act_search, name='act-search'),


    ]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('dispatcher.urls', 'dispatcher'),  namespace='dispatcher')),
    path('__debug__/', include('debug_toolbar.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dispatcher/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
			email=self.normalize_email(email),
			username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.type = 'DISPATCHER'
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default = False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    class Types(models.TextChoices):
        USER = "USER", "User"
        DISPATCHER = "DISPATCHER", "Dispatcher"
        DEPARTMENT_HEAD = "DEPARTMENT_HEAD", "Department_head"
        EXECUTOR = "EXECUTOR", "Executor"

    base_type = Types.USER
    type = models.CharField(
        _("Type"), max_length=50, choices=Types.choices, default=base_type
    )

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    def __str__(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

    def save(self, *args, **kwargs):
        if not self.id:
            self.type = self.base_type
        return super().save(*args, **kwargs)

class UserManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.USER)

class User(Account):
    base_type = Account.Types.USER
    objects = UserManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm user"


class DispatcherManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.DISPATCHER)

class Dispatcher(Account):
    base_type = Account.Types.DISPATCHER
    objects = DispatcherManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm dispatcher"


class DepartmentHeadManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.DEPARTMENT_HEAD)

class DepartmentHead(Account):
    base_type = Account.Types.DEPARTMENT_HEAD
    objects = DepartmentHeadManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm department head"


class ExecutorManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=Account.Types.EXECUTOR)

class Executor(Account):
    base_type = Account.Types.EXECUTOR
    objects = ExecutorManager()

    class Meta:
        proxy = True

    def whisper(self):
        return "i'm executor"

# class ExecutorMore(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     gadgets = models.TextField()


class Act(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now, editable=False)
    date_updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    adress = models.CharField(max_length=200)
    act_type = models.CharField(max_length=20)
    text = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='images/act_images')
    file = models.FileField(null=True, blank=True, upload_to='files/act_files')
    completed = models.BooleanField(default=False)

    class ActProcesses(models.TextChoices):
        waiting = 'Ожидание принятия заявки'
        accepted = 'Заявки принята'
        returned = 'Заявка возвращена'

    act_processing = models.CharField(max_length=25, choices=ActProcesses.choices, default=ActProcesses.waiting)
    do_until = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title

# В каждом меню будет дополнительные подменю. Например:
# Заявки – В работе – Не выполненные – Просроченные – В обработке

dispatcher/forms.py
from django.forms import ModelForm
from .models import Act, Account
from django import forms
from django.contrib.auth.forms import UserCreationForm
# RELEVANCE_CHOICES = (
#     (1, "Сантехника"),
#     (2, "электрика"),
#     (3, "строитель"),
#     (4, "плотник"),
# )

# class ActForm(forms.Form):
#     adress = forms.CharField(label='Точный адресс:Здание, помещение, этаж, кабинет/квартира.', max_length=100, widget=forms.TextInput(attrs={'class': 'formclass'}))
#     type = forms.ChoiceField(label='Тип заявки:',choices = RELEVANCE_CHOICES)
#     full_name = forms.CharField(label='ФИО',max_length=40, widget=forms.TextInput(attrs={'class': 'formclass'}))
#     phone_number = forms.CharField(label='Телефон',max_length=17, widget=forms.TextInput(attrs={'class': 'formclass'}))
#     act_text = forms.CharField(label='Описание',widget=forms.Textarea(attrs={'class': 'formclass'}))

# class CreateUserForm(ModelForm):
#     class Meta:
#         model = auth_user
#         fields = '__all__'

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2',)

class ActForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'special'})
        self.fields['adress'].widget.attrs.update({'class': 'special'})
        self.fields['act_type'].widget.attrs.update({'class': 'special'})
        self.fields['text'].widget.attrs.update({'class': 'special'})
        self.fields['image'].widget.attrs.update({'class': 'special'})

    image = forms.ImageField(required = False)
    file = forms.FileField(required = False)

    class Meta:
        model = Act
        fields = '__all__'
        exclude = ('act_processing', 'do_until', 'user')


class ActSetDateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['do_until'].widget.attrs.update({'class': 'special'})

    class Meta:
        model = Act
        fields = ('do_until',)
        widgets = {
            'do_until': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

# class ActSearch(forms.Form):
#     search = forms.CharField(label='Поиск', max_length=100)

dispatcher/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, View
from django.http import  QueryDict
from django.core.paginator import Paginator
from .forms import RegistrationForm, ActSetDateForm
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.contrib import messages
from django.utils import timezone

from .forms import  ActForm
from .models import Act, Account
from django.db.models import Q

def home(request):
    return render (request, 'dispatcher/home.html',{})

def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request,user)
            messages.success(request,("успешная регистрация"))
            return HttpResponseRedirect('http://127.0.0.1:8000/list/')
    else:
        form = RegistrationForm()

    return render(request, 'dispatcher/registration.html',{'form':form})


class BBLoginView(LoginView):
    template_name = 'dispatcher/login.html'

class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'dispatcher/logout.html'

@login_required
def profile(request):
    return render(request,'dispatcher/profile.html', {})


@login_required
def act_page_create(request):
    form_class = ActForm
    form = form_class(request.POST or None)
    if request.method == 'POST':
        form = ActForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user.id
            form.instance.user_id = user
            form.save()
        return HttpResponseRedirect('http://127.0.0.1:8000/list/')
    else:
        form = ActForm()

    return render(request, 'dispatcher/act.html', {'form': form, })

@login_required
def act_page(request, actid):

    queryset = get_object_or_404(Act, id=actid) #Act.objects.get(id=actid)
    if request.user.id == queryset.user_id or request.user.is_staff == 1:
        if request.method == 'GET':
            return render(request, 'dispatcher/act_page.html', {'act':queryset})
        elif request.method == 'PUT':
            data = QueryDict(request.body).dict()
            form = ActForm(data, instance=queryset)
            if form.is_valid():
                form.save()
                Act.objects.filter(id=actid).update(act_processing='Ожидание принятия заявки')
                return render(request,'dispatcher/details/act-detail.html', {'act':queryset})

            return render(request, 'dispatcher/forms/edit-act-form.html', {'form': form})

    else:
        return render(request, 'dispatcher/no_access.html')

def act_edit_form(request, pk):
    queryset = get_object_or_404(Act, pk=pk)
    form = ActForm(instance=queryset)
    return render(request,'dispatcher/forms/edit-act-form.html',{'act':queryset,'form':form})

def return_act(request, actid):
    if request.user.is_staff == 1:
        Act.objects.filter(id=actid).update(act_processing='Заявка возвращена')

        return render(request, 'dispatcher/details/return-detail.html')

def accept_act(request, actid):
    if request.user.is_staff == 1:
        Act.objects.filter(id=actid).update(act_processing='Заявки принята')
        return render(request, 'dispatcher/details/accept-detail.html')

def set_date(request, actid):
    if request.user.is_staff == 1:
        if request.method == 'GET':
            queryset = Act.objects.filter(id=actid).values_list('do_until', flat=True).first()

            form = ActSetDateForm()#instance=queryset
            return render(request, 'dispatcher/forms/date-form.html', {'form': form,'act':actid, 'date':queryset})
        if request.method == 'PUT':
            # optimize query
            queryset = get_object_or_404(Act, id=actid)
            data = QueryDict(request.body).dict()
            form = ActSetDateForm(data, instance=queryset)
            if form.is_valid():
                form.save()

        return render(request, 'dispatcher/details/accept-detail.html')


@login_required
def act_list(request):

    current_user = request.user
    queryset = Act.objects.filter(user_id=current_user)

    paginator = Paginator(queryset, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'dispatcher/act_list.html', {'acts':queryset, 'page_obj':page_obj})

@login_required
def dispatcher_act_list(request):

    if request.user.is_staff == 1:
        # less queries with select_related?
        queryset = Act.objects.select_related().all().order_by('-date_updated')

        paginator = Paginator(queryset, 15)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'dispatcher/act_list.html', {'acts':queryset, 'page_obj':page_obj})
    else:
        return render(request, 'dispatcher/no_access.html')


def act_status(request):
    status = request.GET.get('status')

    if status == 'all':
        queryset = Act.objects.all().order_by('-date_updated')
    elif status == 'completed':
        queryset = Act.objects.filter(completed=True)
    elif status == 'uncompleted':
        queryset = Act.objects.filter(completed=False)
    elif status == 'new':
        queryset = Act.objects.filter(act_processing='Ожидание принятия заявки')
    elif status == 'expired':
        now = timezone.localtime(timezone.now())
        queryset = Act.objects.filter(do_until__lt=now).exclude(do_until=None)

    return render(request,'dispatcher/details/act-status.html', {'status':queryset} )

def act_search(request):
    if request.method == 'POST':
        # any orm injections?
        search = request.POST['search']
        acts = Act.objects.all()
        queryset = [act for act in acts if (
                    (search.lower() in act.title.lower())
                    or
                    (search.lower() in act.adress.lower())
                    or
                    (search.lower() in act.text.lower())
                )]
        return render(request,'dispatcher/details/act-status.html', {'status':queryset} )


@login_required
def employees_list(request):
    if request.user.is_staff == 1:
        queryset = Account.objects.filter(~Q(type='USER'))

        paginator = Paginator(queryset, 15)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'dispatcher/employees_list.html', {'employees':queryset, 'page_obj':page_obj})
    else:
        return render(request, 'dispatcher/no_access.html')

templates/dispatcher/act.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
 <body>
  {% block content %}
  <style>


  .special {
     line-height: 10px;/*Высота строки +  верт. центрирования текста*/
     font-size: 16px;
     background: rgb(243, 243, 243);
     color: rgb(14, 5, 5);
     margin-left: 30px;
     margin-top: 25px;
     width: 320px; /*Фиксируем ширину блока*/
     margin-right: 10px;
     text-align: center; /*Центрируем текст по горизонтали*/
     border-radius: 3px;
     border-color: rgb(14, 5, 5);
     border-width: 1px;
     resize: none;
  }
  </style>


      <h5> Заявка</h5>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

       {{ form.as_ul }}

<!-- 
       {{form.user.label_tag}}
       {{form.user}} <br>

       {{form.title.label_tag}}
       {{form.title}} <br>

       {{form.adress.label_tag}}
       {{form.adress}}<br>

       {{form.act_type.label_tag}}
       {{form.act_type}}<br>

       {{form.text.label_tag}}
       {{form.text}}<br>

       {{form.image.label_tag}}
       {{form.image}}<br> -->

        <input type="submit" value="Отправить">
      </form>




  {% endblock %}

  </body>

</html>

templates/dispatcher/act_list.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <style>
    #center {
      width: 1700px;
      height: 750px;
      border: 5px solid #333;
      border-top-width: 0px;
      border-bottom-right-radius: 25px;
      border-bottom-left-radius: 25px;
      background-image: linear-gradient(rgb(255, 255, 255), rgb(255, 255, 255), rgb(255, 255, 255),rgb(255, 255, 255),rgb(255, 255, 255),rgb(173, 252, 166));
    }
    
    .row{
      margin-top: 20px;

    }
  </style>

</head>
    {% block content %}

<!-- HTMX -->
<script src="https://unpkg.com/htmx.org@1.6.1"></script>

{% if act_sent %}
<br>
<H6>Заявка отправленна</H6>
<br>
{% endif %}



<form hx-post="search" hx-target="#body" hx-swap="outerHTML">
    {% csrf_token %}
    <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск" name="search">
    <input class="btn btn-primary" type="submit" value="Найти"/>
</form> 

<br>

<div>
  <label >Сортировать по:</label>
  <select name="make" hx-get="/models" hx-target="#models" hx-indicator=".htmx-indicator">
    <option value="audi">Дате изменения заявки</option>
    <option value="toyota">Дате создания заявки</option>
  </select>
</div>

<br>

<div>
  <label >Заявки:</label>
  <select name="status" hx-get="status" hx-target="#body" hx-swap="outerHTML" hx-indicator=".htmx-indicator">
    <option value="all">Все</option>
    <option value="completed">Выполненные</option>
    <option value="uncompleted">Не выполненные</option>
    <option value="new">Новые</option>
    <option value="expired">Просроченные</option>
  </select>
</div>





 <hr>
<table id="body">
  <thead>
    <tr>
      <th>User name</th>
      <th>Title</th>
      <th>Adress</th>
      <th>Act type</th>
      <th>Date created</th>
      <th>Date updated</th>
      <th>Url</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in page_obj %}
    <tr>
      <td>{{obj.user}}</td>
      <td>{{obj.title}}</td>
      <td>{{obj.adress}}</td>
      <td>{{obj.act_type}}</td>
      <td>{{obj.date_created}}</td>
      <td>{{obj.date_updated}}</td>      
      <td><a href="http://127.0.0.1:8000/act/{{obj.id}}">Смотреть заявку</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>



{% if page_obj.has_previous %}
<a href="?page=1">&laquo First</a>
<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">next</a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
{% endif %}


  {% endblock %}

  </body>

</html>

templates/dispatcher/act_page.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}

{% block title %}Заявка{% endblock %}


{% block content %}

<!-- HTMX -->
<script src="https://unpkg.com/htmx.org@1.6.1"></script>

<div class="container mt-4">

  <div id="act-details">
    {% include 'dispatcher/details/act-detail.html' %}
  </div>


  
  {% if request.user.is_staff == 1 %}
  <button hx-get="return" hx-target="this" hx-swap="outerHTML">
    Вернуть заявку
  </button>
  <button hx-get="accept" hx-target="this" hx-swap="outerHTML">
    Принять заявку
  </button>
  
  <br>
  <br>

  <button id="date-detail" hx-get="date" hx-target="this" hx-swap="outerHTML">
    Выставить дату
  </button>

  {% else %}

  {% endif %}



  <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
  </script>
</div>
{% endblock %}

templates/dispatcher/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

  
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
  
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  
  
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}



</style>
</head>
<body>
  
<div class="topnav">
  <a class="active" href="http://127.0.0.1:8000">Home</a>
  <a href="/act/">Создать заявку</a>
  <a href="/list/">Смотреть заявки</a>
  <a href="/profile/">Профиль</a>
  {% if user.is_authenticated %}<a href="{% url 'dispatcher:logout' %}">Выход</a>
  {% else %}
  <a href="{% url 'dispatcher:register' %}">Регистрация</a>
  <a href="{% url 'dispatcher:login' %}">Вход</a>
  {% endif %}
  <a href="/dispatcher/list">Все заявки</a>
  <a href="">Отчёты</a>
  <a href="{% url 'dispatcher:employees_list' %}">Сотрудники</a>
  <a href="">Телефония</a>
  <a href="">Объекты</a>



</div>

<hr>
{% block content %}
{% endblock %}




</body>
</html>

templates/dispatcher/create_user.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
{% block content %}


<h5> Создать пользователя</h5>
<form action="{{HttpResponse}}" method="post">
  {% csrf_token %}

  <div><br>{{form}}</br></div>

  <input type="submit" value="Submit">
</form>
















{% endblock %}
</body>
</html>

templates/dispatcher/employees_list.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">


 

</head>
    {% block content %}



{% if act_sent %}
<br>
<H6>Заявка отправленна</H6>
<br>
{% endif %}



  



<h3> 
  Поиск 
  <span class="htmx-indicator"> 
    <img src="/img/bars.svg"/> Searching... 
   </span> 
</h3>

<!-- test sql injection -->
<input class="form-control" type="search" 
       name="search" placeholder="Begin Typing To Search Users..." 
       hx-post="/search" 
       hx-trigger="keyup changed delay:500ms, search" 
       hx-target="#search-results" 
       hx-indicator=".htmx-indicator">

       <br>
       <br>

<table class="table">
    <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
    </tr>
    </thead>
    <tbody id="search-results">
    </tbody>
</table>

<br>

<div>
  <label >Сортировать по:</label>
  <select name="make" hx-get="/models" hx-target="#models" hx-indicator=".htmx-indicator">
    <option value="audi">Дате изменения заявки</option>
    <option value="toyota">Дате создания заявки</option>
  </select>
</div>




 <hr>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th>Date joined</th>
      <th>Last login</th>
      <th>Сотрудник</th>
      <th>Url</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
    <tr>
      <td>{{employee.email}}</td>
      <td>{{employee.username}}</td>
      <td>{{employee.date_joined}}</td>
      <td>{{employee.last_login}}</td>
      <td>{{employee.type}}</td>
      <td><a href="http://127.0.0.1:8000/act/{{obj.id}}">Смотреть заявку</a></td>
    
    </tr>
    {% endfor %}
  </tbody>
</table>



{% if page_obj.has_previous %}
<a href="?page=1">&laquo First</a>
<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">next</a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
{% endif %}


  {% endblock %}

  </body>

</html>

templates/dispatcher/home.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
{% block content %}


<h5> Главная</h5>
















{% endblock %}
</body>
</html>

templates/dispatcher/login.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


{% block title %}Вход{% endblock %}

    {% block content %}

{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
  {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endif %}

<form method="post" action="{% url 'dispatcher:login' %}">
{% csrf_token %}
<table>

<tr>
  <td>{{ form.username.label_tag }}</td>
  <td>{{ form.username }}</td>
</tr>

<tr>
  <td>{{ form.password.label_tag }}</td>
  <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>




    {% endblock %}
</body>
</html>

templates/dispatcher/registration.html
<!DOCTYPE html>
{% extends "dispatcher/base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


{% block title %}Регистрация{% endblock %}

    {% block content %}

{% if form.errors %}
  <p>Please try again.</p>
{% endif %}


<form method="post" action="{% url 'dispatcher:register' %}">
{% csrf_token %}
{{ form }}

<input type="submit" value="register" />
<input type="hidden" name="next" value="{{ next }}" />
</form>




    {% endblock %}
</body>
</html>